services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tlece_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./tlece_app:/var/www
    env_file:
      - ./tlece_app/.env
    depends_on:
      - mysql
    networks:
      - tlece_app_network

  mysql:
    image: mysql:8
    container_name: tlece_mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tlece_db
      MYSQL_USER: tlece_user
      MYSQL_PASSWORD: tlece_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tlece_app_network

  nginx:
    image: nginx:alpine
    container_name: tlece_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./tlece_app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - tlece_app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tlece_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - tlece_app_network

networks:
  tlece_app_network:
    driver: bridge

volumes:
  mysql_data:
